### ISSUE TITLE
link to pagefreezer-cli repo

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/DataRescueNYC#5]
soon as we get https://github.com/edgi-govdata-archiving/pagefreezer-cli into any kind of a state we should link to it from here.

**Comment by dcwalk** [comment]
Agree! I've been grouping our projects as: 

WEBSITE MONITORING
https://github.com/edgi-govdata-archiving/pagefreezer-tools
https://github.com/edgi-govdata-archiving/pagefreezer-cli

https://github.com/edgi-govdata-archiving/version-tracking-ui
https://github.com/edgi-govdata-archiving/versionista-outputter

DATARESCUE and PIPELINE
** https://github.com/edgi-govdata-archiving/workflow
https://github.com/edgi-govdata-archiving/s3-upload-server
** https://github.com/edgi-govdata-archiving/zip-starter
https://github.com/edgi-govdata-archiving/harvesting-tools
(Pipeline repo)

Toolkit/remote contribution process **++**
   https://github.com/edgi-govdata-archiving/overview
   https://github.com/edgi-govdata-archiving/workflow

**Comment by dcwalk** [comment]
I think we update overview to reflect that grouping, and link from here as well

**Comment by dcwalk** [comment]
Also! What about ckan development! That is ongoing as well!

**Comment by titaniumbones** [comment]
yes, if you can possibly do it today -- I know you're crazy busy! --
thx.  prepping for class rt now, sorta.

**Comment by dcwalk** [comment]
I can! I've gotta turn my attention elsewhere but can circle back on this mid afternoon

**Comment by titaniumbones** [comment]
yeah, agreed. I know so little about that i couldn't write anything &
can't really "moderate" that conversation but that might be a good place
for Laurie or someone else to intervene?

**Comment by dcwalk** [comment]
Closing as complete
