### ISSUE TITLE
Remember to tell organizers that you love them!

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/DataRescueNYC#9]
There's still time to tell @b5 @ebarry @dallan  Maya @ambergman @trinberg @jaclynweiser  Sarah L  SJ that you appreciate their work and commitment! Fantastic work folks, always a pleasure and a privilege to work with you!

**Comment by dcwalk** [comment]
Want to second this 👍 a pleasure to work with you folks 😀

**Comment by titaniumbones** [comment]
I don't know **WHEN** I will be able to close this... how will I know if there's been enough love?

**Comment by b5** [comment]
Agreed! Everyone it's been a wonderful opportunity to work with all of you 😃
